let x = [
  "Is Israel a Colonial, Imperialist State?",
  "Did European Jews Displace Palestinians?",
  "Was the Zionist Movement a Plot to Colonize All of Palestine?",
  "Was the Balfour Declaration Binding International Law?",
  "Were the Jews Unwilling to Share Palestine?",
  "Have the Jews Always Rejected the Two-State Solution?",
  "Have the Jews Exploited the Holocaust?",
  "Was the U.N. Partition Plan Unfair to Palestinians?",
  "Were Jews a Minority in What Became Israel?",
  "Has Israel’s Victimization of the Palestinians Been Primary Cause of the Arab–Israeli Conflict?",
  "Was the Israeli War of Independence Expansionist Aggression?",
  "Did Israel Create the Arab Refugee Problem?",
  "Did Israel Start the Six-Day War?",
  "Was the Israeli Occupation without Justification?",
  "Was the Yom Kippur War Israel’s Fault?",
  "Has Israel Made Serious Efforts at Peace?",
  "Was Arafat Right in Turning Down the Barak–Clinton Proposal?",
  "Why Have More Palestinians Than Israelis Been Killed?",
  "Does Israel Torture Palestinians?",
  "Has Israel Engaged in Genocide against Palestinian Civilians?",
  "Is Israel a Racist State?",
  "Is the Israeli Occupation the Cause of All the Problems?",
  "Has Israel Denied the Palestinians Statehood?",
  "Is Israel’s Policy of House Destruction Collective Punishment?",
  "Is Targeted Assassination of Terrorist Leaders Unlawful?",
  "Is Settlement in the West Bank and Gaza a Major Barrier Peace?",
  "Is Terrorism Merely Part of a Cycle of Violence?",
  "Is Israel the Prime Human Rights Violator in the World?",
  "Is There Moral Equivalence between Palestinian Terrorists and Israeli Responses?",
  "Should Universities Divest from Israel and Boycott Israeli Scholars?",
  "Are Critics of Israel Anti-Semitic?",
  "Why Do So Many Jews and Even Israelis Side with Palestinians?"
]

export default x;
